version: "3.7"

volumes:
  postgres_data:

networks:
  backend:

services:
  postgres:
    image: postgres:10.6-alpine
    ports:
      - ${PGSQL_PORT:-5432}:5432
    volumes:
      # We'll store the postgres data in the 'postgres_data' volume we defined:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: 3x4mpl3P455w0rd